# Generated by Django 2.2.7 on 2019-12-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.People')),
                ('numQuestions', models.PositiveIntegerField(default=0)),
                ('numCorrect', models.PositiveIntegerField(default=0)),
                ('userFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='homepage.People')),
            ],
            bases=('homepage.people',),
        ),
    ]
