# Generated by Django 2.2.7 on 2019-12-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='hashPass',
            field=models.CharField(max_length=30),
        ),
    ]
