# Generated by Django 2.2.7 on 2019-12-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='people_ptr',
        ),
        migrations.RemoveField(
            model_name='score',
            name='userFK',
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
