# Generated by Django 2.2.7 on 2019-11-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='rightWrong',
            new_name='isRight',
        ),
    ]
